//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18033
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircleLogicPortal.ImageSlideWebPart {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class ImageSlideWebPart {
        
        public static implicit operator global::System.Web.UI.TemplateControl(ImageSlideWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::CircleLogicPortal.ImageSlideWebPart.ImageSlideWebPart @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n\r\n\r\n<script type=\"text/javascript\" src=\"");
                            @__w.Write(ImgUrl);

            @__w.Write("jquery.infinitecarousel2.js\" ></script>\r\n<script type=\"text/javascript\">\r\n   \r\n  " +
                    "  ExecuteOrDelayUntilScriptLoaded(");
                            @__w.Write(this.ClientID);

            @__w.Write("Initialize, \"sp.js\");\r\n       \r\n    //Retrieve  the Tab items\r\nfunction ");
 @__w.Write(this.ClientID);

            @__w.Write(@"Initialize() {
    //Get the current SP context

    var camlQuery = new SP.CamlQuery();
	
    var q = ""<View Scope='RecursiveAll'><Query><Where><Eq><FieldRef Name='FSObjType' /><Value Type='Integer'>0</Value></Eq></Where><OrderBy><FieldRef Name='Modified' Ascending='FALSE' /></OrderBy></Query><RowLimit>");
                                                                                                                                                                                                              @__w.Write(ItemCount);

            @__w.Write("</RowLimit></View>\";\r\n\r\n    camlQuery.set_viewXml(q);\r\n\r\n    ");
       if (ListName.Trim()!="")    { 
       if (WebName.Trim() != "")
       { 
            @__w.Write("\r\n    clientContext = new SP.ClientContext(\"");
                                  @__w.Write(WebName.Trim());

            @__w.Write("\");\r\n    ");
       }else { 
            @__w.Write("\r\n    clientContext = new SP.ClientContext.get_current();\r\n    ");
       } 
            @__w.Write("\r\n    web = clientContext.get_web();\r\n    this.");
 @__w.Write(this.ClientID );

            @__w.Write("list = web.get_lists().getByTitle(\'");
                                                       @__w.Write(ListName.Trim());

            @__w.Write("\');\r\n    \r\n    this.");
 @__w.Write(this.ClientID );

            @__w.Write("listItems = ");
                                @__w.Write(this.ClientID );

            @__w.Write("list.getItems(camlQuery);\r\n    \r\n    clientContext.load(");
               @__w.Write(this.ClientID );

            @__w.Write("list,\"DefaultDisplayFormUrl\",\"BaseTemplate\",\"RootFolder\");\r\n    clientContext.loa" +
                    "d(");
               @__w.Write(this.ClientID );

            @__w.Write("listItems,\'Include(ID,FileLeafRef,FileDirRef)\');\r\n    \r\n    clientContext.execute" +
                    "QueryAsync(Function.createDelegate(this, this.");
                                                               @__w.Write(this.ClientID);

            @__w.Write("onListItemsLoadSuccess), Function.createDelegate(this, this.onListItemsLoadFailed" +
                    "));\r\n    ");
       } 
            @__w.Write("\r\n\r\n    \r\n}\r\n\r\nfunction onListItemsLoadFailed(sender, args) {\r\n\tSP.UI.Notify.addN" +
                    "otification(\"List items load failed: \" + args.get_message(), false);\r\n}\r\nfunctio" +
                    "n ");
 @__w.Write(this.ClientID);

            @__w.Write("onListItemsLoadSuccess(sender, args) {\r\n\t");
    if (ListName!="")    { 
            @__w.Write("\r\n    try{\r\n        var listtype = ");
               @__w.Write(this.ClientID );

            @__w.Write("list.get_baseTemplate();\r\n    \r\n        var listEnumerator = this.");
                          @__w.Write(this.ClientID );

            @__w.Write("listItems.getEnumerator();\r\n        var listurl = ");
              @__w.Write(this.ClientID );

            @__w.Write(@"list.get_rootFolder().get_serverRelativeUrl();
        
        while (listEnumerator.moveNext()) {
            itemHtml = """";

            var oListItem = listEnumerator.get_current();
            var filename = oListItem.get_item('FileLeafRef');
            //filename = filename.replace('.', '_');
            //filename += '.jpg';
            var dir = oListItem.get_item('FileDirRef');
            //filename = dir + '/_t/' + filename;
            filename = dir + '/' + filename;
            itemHtml +=""<li>""+
                            ""<table width='");
                                   @__w.Write(Convert.ToInt32(ImgWidth) + 10);

            @__w.Write("px\' padding=\'0\' margin=\'0\' border=\'0\'>\"+\r\n                                \"<tr>\"+" +
                    "\r\n                                    \"<td width=\'");
                                        @__w.Write(ImgWidth);

            @__w.Write("px\' align=\'center\' valign=\'top\'>\"+\r\n                                        \"<a h" +
                    "ref=\'\" + filename + \"\' onfocus=\'this.blur()\'>\"+\r\n                               " +
                    "            \"<img src=\'\" +filename+ \"\' width=\'");
                                                                     @__w.Write(ImgWidth);

            @__w.Write("px\' style=\'max-height:");
                                                                                                        @__w.Write(ImgHeight);

            @__w.Write(@"px; border:#000000 1px solid;'/>""+
                                        ""</a>""+
                                    ""</td>""+
                                ""</tr>""+
                            ""</table>""+
                        ""</li>"";
            //itemHtml += ""<img src='"" + filename + ""' width='");
                                                      @__w.Write(ImgWidth);

            @__w.Write("px\' height=\'");
                                                                               @__w.Write(ImgHeight);

            @__w.Write("px\'   id=\'\" + oListItem.get_item(\"ID\") + \"\'/>\";\r\n\t\t    jQuery(\'#");
       @__w.Write(this.ClientID );

            @__w.Write("_carousel ul\').append(itemHtml);\r\n        }\r\n        //jQuery(\'#");
           @__w.Write(this.ClientID );

            @__w.Write("_link1\').attr(\"href\",");
                                                   @__w.Write(this.ClientID );

            @__w.Write("list1.get_rootFolder().get_serverRelativeUrl());\r\n        \r\n        jQuery(functi" +
                    "on(){\r\n\t        jQuery(\'#");
          @__w.Write(this.ClientID );

            @__w.Write("_carousel\').infiniteCarousel(\r\n            {\r\n                imgWidth:");
                 @__w.Write(Convert.ToInt32(ImgWidth) + 10);

            @__w.Write(",\r\n                imgHeight:");
                  @__w.Write(Convert.ToInt32(ImgHeight)+10);

            @__w.Write(",\r\n                imagePath:\'");
                   @__w.Write(ImgUrl);

            @__w.Write("\',\r\n                advance:");
                @__w.Write(ViewCount);

            @__w.Write(",\r\n                autoStart:");
                  @__w.Write(AutoPlay.ToString().ToLower());

            @__w.Write(",\r\n                displayTime:");
                    @__w.Write(DisplayTime);

            @__w.Write(",\r\n                showControls:");
                     @__w.Write(ShowButton.ToString().ToLower());

            @__w.Write("\r\n            });\r\n            jQuery(\'#");
             @__w.Write(this.ClientID );

            @__w.Write("_carousel\').css(\'display\',\'block\');\r\n        });\r\n    }\r\n    catch(err)\r\n    {\r\n " +
                    "   }\r\n    ");
       } 
            @__w.Write("\r\n}\r\n</script>\r\n<div id=\'");
 @__w.Write(this.ClientID );

            @__w.Write("_carousel\' style=\'display:none;\'>\r\n<ul>\r\n\r\n</ul>\r\n</div>");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
