//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18033
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircleLogicPortal.TabListWebpart {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class TabListWebpart {
        
        public static implicit operator global::System.Web.UI.TemplateControl(TabListWebpart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::CircleLogicPortal.TabListWebpart.TabListWebpart @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write(@"


<script type=""text/javascript"">
   
    ExecuteOrDelayUntilScriptLoaded(Initialize, ""sp.js"");
    function openDialog(_url) {  
        var options = {  url: _url ,  width: 800, height: 600, };  
        SP.UI.ModalDialog.showModalDialog(options);  
    }

    //Retrieve  the Tab items
function Initialize() {
    //Get the current SP context
    clientContext = new SP.ClientContext.get_current();
    web = clientContext.get_web();
    
	var camlQuery = new SP.CamlQuery();
	
    var q = ""<View><Query><Where><Neq><FieldRef Name='ContentType' /><Value Type='Computed'>Folder</Value> </Neq></Where><OrderBy><FieldRef Name='Modified' Ascending='FALSE' /></OrderBy><QueryOptions><RowLimit>");
                                                                                                                                                                                                          @__w.Write(ListItemCount);

            @__w.Write("</RowLimit></QueryOptions></Query></View>\";\r\n    camlQuery.set_viewXml(q);\r\n\r\n   " +
                    " ");
       if (ListName1!="")    { 
            @__w.Write("\r\n    this.list1 = web.get_lists().getByTitle(\'");
                                     @__w.Write(ListName1);

            @__w.Write("\');\r\n    this.listItems1 = list1.getItems(camlQuery);\r\n    clientContext.load(lis" +
                    "t1);\r\n    clientContext.load(listItems1);\r\n    ");
       } 
       if (ListName2!="")    { 
            @__w.Write("\r\n    this.list2 = web.get_lists().getByTitle(\'");
                                     @__w.Write(ListName2);

            @__w.Write("\');\r\n    this.listItems2 = list2.getItems(camlQuery);\r\n    clientContext.load(lis" +
                    "t2);\r\n    clientContext.load(listItems2);\r\n    ");
       } 
       if (ListName3!="")    { 
            @__w.Write("\r\n    this.list3 = web.get_lists().getByTitle(\'");
                                     @__w.Write(ListName3);

            @__w.Write("\');\r\n    this.listItems3 = list3.getItems(camlQuery);\r\n    clientContext.load(lis" +
                    "t3);\r\n    clientContext.load(listItems3);\r\n    ");
       } 
            @__w.Write(@"

    clientContext.executeQueryAsync(Function.createDelegate(this, this.onListItemsLoadSuccess), Function.createDelegate(this, this.onListItemsLoadFailed));
}

/*
*
* Initialize delegate function: this function adds the returned items to the HTML lists.
*
*/

function onListItemsLoadSuccess(sender, args) {
	");
    if (ListName1!="")    { 
            @__w.Write("\r\n    $(\'#");
@__w.Write(this.ClientID );

            @__w.Write(@"_tab1 ul li').remove();
    var listtype1 = list1.get_baseTemplate()
    var listEnumerator = this.listItems1.getEnumerator();
    while (listEnumerator.moveNext()) {
        //Retrieve the current list item
        var oListItem = listEnumerator.get_current();
		//Add the items to the list
		var itemHtml = ""<li ref='"" + oListItem.get_item('ID') + ""'>"";
			itemHtml += ""<a href='#' title='Mark as completed' onClick='javascript:MarkAsComplete("" + oListItem.get_item('ID') + ""); return false;'><img src='/_layouts/images/CHECK.GIF' /></a>"";
			itemHtml += ""<a href='#' title='Delete to-do item' onClick='javascript:DeleteItem("" + oListItem.get_item('ID') + ""); return false;'><img src='/_layouts/images/delete.GIF' /></a>"";
			itemHtml += oListItem.get_item('Title') + ""</li>"";
		$('#");
@__w.Write(this.ClientID );

            @__w.Write("_tab1 ul\').append(itemHtml);\r\n    }\r\n    ");
       } 
       if (ListName2!="")    { 
            @__w.Write("\r\n    $(\'#");
@__w.Write(this.ClientID );

            @__w.Write(@"_tab2 ul li').remove();
    var listtype2 = list2.get_baseTemplate()
	listEnumerator = this.listItems2.getEnumerator();
    while (listEnumerator.moveNext()) {
        //Retrieve the current list item
        var oListItem = listEnumerator.get_current();
		//Add the items to the list
		var itemHtml = ""<li ref='"" + oListItem.get_item('ID') + ""'>"";
			itemHtml += ""<a href='#' onClick='javascript:MarkAsComplete("" + oListItem.get_item('ID') + ""); return false;'><img src='/_layouts/images/CHECK.GIF' /></a>"";
			itemHtml += ""<a href='#' onClick='javascript:DeleteItem("" + oListItem.get_item('ID') + ""); return false;'><img src='/_layouts/images/delete.GIF' /></a>"";
			itemHtml += oListItem.get_item('Title') + ""</li>"";
		$('#");
@__w.Write(this.ClientID );

            @__w.Write("_tab2 ul\').append(itemHtml);\r\n    }\r\n    ");
       } 
       if (ListName3!="")    { 
            @__w.Write("\r\n    $(\'#");
@__w.Write(this.ClientID );

            @__w.Write(@"_tab3 ul li').remove();
    var listtype3 = list3.get_baseTemplate()
    listEnumerator3 = this.listItems3.getEnumerator();
    while (listEnumerator.moveNext()) {
        //Retrieve the current list item
        var oListItem = listEnumerator.get_current();
		//Add the items to the list
		var itemHtml = ""<li ref='"" + oListItem.get_item('ID') + ""'>"";
			itemHtml += ""<a href='#' title='Mark as completed' onClick='javascript:MarkAsComplete("" + oListItem.get_item('ID') + ""); return false;'><img src='/_layouts/images/CHECK.GIF' /></a>"";
			itemHtml += ""<a href='#' title='Delete to-do item' onClick='javascript:DeleteItem("" + oListItem.get_item('ID') + ""); return false;'><img src='/_layouts/images/delete.GIF' /></a>"";
			itemHtml += oListItem.get_item('Title') + ""</li>"";
		$('#");
@__w.Write(this.ClientID );

            @__w.Write("_tab3 ul\').append(itemHtml);\r\n    }\r\n\t");
    } 
            @__w.Write("\r\n}\r\nfunction onListItemsLoadFailed(sender, args) {\r\n\tSP.UI.Notify.addNotificatio" +
                    "n(\"List items load failed: \" + args.get_message(), false);\r\n}\r\n    \r\n</script>\r\n" +
                    "\r\n\r\n");
@__w.Write(ImgUrl);

            @__w.Write("<br />\r\n");
@__w.Write(ListItemCount );

            @__w.Write("<br />\r\n");
@__w.Write(WebName1);

            @__w.Write("<br />\r\n");
@__w.Write(WebName2);

            @__w.Write("<br />\r\n");
@__w.Write(WebName3);

            @__w.Write("<br />\r\n");
@__w.Write(ListName1);

            @__w.Write("<br />\r\n");
@__w.Write(ListName2);

            @__w.Write("<br />\r\n");
@__w.Write(ListName3);

            @__w.Write("<br />\r\n<div class=\"container\" id=\"");
                   @__w.Write(this.ClientID );

            @__w.Write("\"_container\">\r\n <div id=\"tabhead\">\r\n  <ul id=\"nav\">\r\n");
   if (ListName1!="")    { 
            @__w.Write("\r\n   <li>\r\n    <a class=\"active\" onclick=\'");
                       @__w.Write(this.ClientID );

            @__w.Write("_changeClass(this,\"");
                                                             @__w.Write(this.ClientID );

            @__w.Write("_tab1\")\' href=\"#\">");
                                                                                                  @__w.Write(ListName1);

            @__w.Write("</a>\r\n   </li>\r\n");
   } 
   if (ListName2!="")    { 
            @__w.Write("\r\n   <li>\r\n    <a onclick=\'");
        @__w.Write(this.ClientID );

            @__w.Write("_changeClass(this,\"");
                                              @__w.Write(this.ClientID );

            @__w.Write("_tab2\")\' href=\"#\">");
                                                                                   @__w.Write(ListName2);

            @__w.Write("</a>\r\n   </li>\r\n");
   } 
   if (ListName3!="")    { 
            @__w.Write("\r\n   <li>\r\n    <a onclick=\'");
        @__w.Write(this.ClientID );

            @__w.Write("_changeClass(this,\"");
                                              @__w.Write(this.ClientID );

            @__w.Write("_tab3\")\' href=\"#\">");
                                                                                   @__w.Write(ListName3);

            @__w.Write("</a>\r\n   </li>\r\n");
   } 
            @__w.Write("\r\n  </ul>\r\n </div>\r\n");
   if (ListName1!="")    { 
            @__w.Write("\r\n <div class=\"tab\" id=\"");
              @__w.Write(this.ClientID );

            @__w.Write("_tab1\">\r\n  <ul id=\"");
  @__w.Write(this.ClientID );

            @__w.Write("_ul1\">\r\n  \r\n  </ul>  \r\n      \r\n  <div style=\"width: 100%;\">\r\n   <span style=\"floa" +
                    "t: right;\"><a id=\"");
                              @__w.Write(this.ClientID );

            @__w.Write("_link1\" href=\"\">more</a></span>\r\n  </div>\r\n </div>\r\n");
   } 
   if (ListName2!="")    { 
            @__w.Write("\r\n <div class=\"tab\" id=\"");
              @__w.Write(this.ClientID );

            @__w.Write("_tab2\" style=\"display: none;\">\r\n  <ul id=\"");
  @__w.Write(this.ClientID );

            @__w.Write("_ul2\">\r\n  \r\n  </ul>\r\n      \r\n  <div style=\"width: 100%;\">\r\n   <span style=\"float:" +
                    " right;\"><a id=\"");
                              @__w.Write(this.ClientID );

            @__w.Write("_link2\" href=\"\">more</a></span>\r\n  </div>\r\n  \r\n </div>\r\n");
   } 
   if (ListName3!="")    { 
            @__w.Write("\r\n <div class=\"tab\" id=\"");
              @__w.Write(this.ClientID );

            @__w.Write("_tab3\" style=\"display: none;\">\r\n  <ul id=\"");
  @__w.Write(this.ClientID );

            @__w.Write("_ul3\">\r\n  \r\n  </ul>\r\n  \r\n  <div style=\"width: 100%;\">\r\n   <span style=\"float: rig" +
                    "ht;\"><a id=\"");
                              @__w.Write(this.ClientID );

            @__w.Write("_link3\"  href=\"\">more</a></span>\r\n  </div>\r\n  \r\n </div>\r\n\r\n");
   } 
            @__w.Write("\r\n</div>");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
